# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=17


## Environment Properties

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)

forge_version=40.3.12
forge_version_range=[40,)
forge_loader_version_range=[40,)

mapping_channel=official
mapping_version=1.18.2

fabric_version=0.77.0+1.18.2
fabric_loader_version=0.16.9
fabric_loader_version_range=>=0.16.0
fabric_loom_version=1.7-SNAPSHOT
fabric_minecraft_version_range=>=1.18.2 <1.19


## Mod Properties

mod_id=modpack_authors
mod_name=Modpack Authors
mod_license=MIT
mod_version=0.2.0
mod_group_id=com.modpackauthors
mod_authors=Modpack Authors
mod_description=Adds a client-side authors and team screen for Minecraft modpacks.
